apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  annotations:
    pv.beta.kubernetes.io/gid: "0" 
spec:
  capacity:
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: jenkins 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
